image: ruby:2.3

pages:
  stage: build
  script:
  - gem install jekyll
  - jekyll build -d public
  - gem build forty_jekyll_theme.gemspec
  artifacts:
    paths:
    - public
    - "forty_jekyll_theme-*.gem"
  only:
  - master