# site settings
title: The Kuo Lab
subtitle: Integrative Behavioral & Evolutionary Ecology
email: kuochiyun@gmail.com
description: Thank you for checking us out!
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "chiyun0529.github.io" # the base hostname & protocol for your site
author:
street_address: N921 1st Teaching Bldg <br /> 100 Shih-Chuan 1st Rd
city: Kaohsiung City 
state: 
zip_code: 80707
country: Taiwan
phone: +886-7-312-1101 ext 2693

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/chiyun0529
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: https://twitter.com/ChifromT
  Facebook:
  Slack:
  Researchgate: https://www.researchgate.net/profile/Chi-Yun-Kuo

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- landing.md
- generic.md
- all_posts.md
- elements.md
