# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# Site settings
title: Trevor's Blog
subtitle: Notes from my learning and daily work!
email: oumei.vip@gmail.com
description: >
  A Fullstack engineer </br> 
  A Mobile Application Developer </br> 
  8+ years for mobile application development including Android & iOS platforms </br>  
  Having knowledges with Ruby, Nodejs, Java, Kotin, Swift etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://trevorwang.github.io" # the base hostname & protocol for your site
author: Trevor Wang
twitter_username: trevorwang
github_username:  trevorwang

google_analytics: UA-91564813-1
disqus:
  shortname: mings-in
# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
