# Site settings
title: Katie Mummah
subtitle: by HTML5 UP
email: radioactivekate@gmail.com
phone: (630) 200-1719
description: > # this means to ignore newlines until "baseurl:"
  Personal website for Katie Mummah
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nuclearkatie.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nuclearkatie
github_username:  nuclearkatie


subtitle:

author:


# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/u/nuclearkatie
# gitlab_url:
linkedin_url: https://www.linkedin.com/in/nuclearkatie
twitter_url: https://twitter.com/nuclearkatie

# build settings
markdown: kramdown

sass:
  style: compressed
