# site settings
title: Lab.Addict
subtitle:
email: jay.a.lewis@gmail.com
description: Home-Lab portfolio focused around Virtualization <br /> Storage Servers and other Technology.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 280 Hillside Ave
city: Palisades Park
state: NJ
zip_code: 07650
country: United States of America
phone: (201) 403-8392

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/jayrel92
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/jerellewis92/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
