# site settings
title: Devol
subtitle: Un web più libero è possibile
description: Un web più libero è possibile.
baseurl: "/devol-website" # the subpath of your site, e.g. /blog
url: https://LeonardoMantovani.github.io # the base hostname & protocol for your site

# recapiti
email: admin@devol.it
newsletter: https://buttondown.email/devol
stanza-matrix: https://chat.mozilla.org/#/room/#mastodon:mozilla.org
pagina-ko-fi: https://ko-fi.com/devol
pagina-coindrop: https://coindrop.to/devol

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 12

# profili social (fedi-socials' keys must match the name of a fedicon icon,
# socials' keys must match name of font awesome 4 icon)
fedi-socials:
  Telegram: https://t.me/devolitalia
  Mastodon: https://mastodon.uno/@devol
  Peertube:
  Writefreely:
  Pixelfed: https://pixelfed.uno/devol
  Funkwhale:
  Mobilizon:
  Gitea: https://gitea.it/devol/

socials:
  GitHub: https://github.com/devolitalia

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
