# site settings
title: CGR LAB
subtitle: "@ Hanyang University"
email: youremailaddress@gmail.com
description: Our research group aims to understand various aspects (movements, structure designs, underlying mechanisms, etc.) of natural or artificial creatures (humans, animals,  robots, etc.) and realize them in from virtual environment to real world.
baseurl: # the subpath of your site, e.g. /blog
url: https://cgrhyu.github.io/ # the base hostname & protocol for your site
author:
street_address: # hard-coded to footer.htm
city: # hard-coded to footer.htm
state: # hard-coded to footer.htm
zip_code: # hard-coded to footer.htm
country: # hard-coded to footer.htm
phone: # hard-coded to footer.htm

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 60

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
