# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: IMS
title-normal: High tech, low stress
email: info@imsysllc.com
description: Automation, Security Systems, Home Theatre, Corporate Boardroom. We do it all.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://andrewbanchich.gitlab.io" # the base hostname & protocol for your site
author:
street_address: 1500 1st Ave S
city: Birmingham
state: AL
zip_code: 35205
country: United States of America
phone: (205) 956 4545

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: https://www.facebook.com/IMSYSLLC?fref=ts
github_url: https://github.com/simplesitesbham/IntegratedMediaSolutions
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/1/110235157727111109913
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/IMSLLC1

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: IMSLLC1
# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:
