# site settings
title: Malcolm's Portfolio
subtitle: by Macworks
email: macworks273@gmail.com
description: My portfolio content contains my development of PowerBi & Tableau dashbaords. Along with my extensive photography collection
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: N
state: 
zip_code:
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/macpsi
  GitLab:
  Instagram: https://www.instagram.com/_macworks_/
  LinkedIn: https://www.linkedin.com/in/malcolm-sims/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
