# site settings
title: Computer Science + Social Good
subtitle: at UNC Chapel Hill
email: cssgunc@gmail.com
description: Fostering discussions and actions for ethical uses of technology, <br />with an aim to give back to UNC and the greater community through our projects and collaborations.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 201 S. Columbia Street
city: Chapel Hill
state: NC
zip_code: 27599
country: United States of America
phone: (919) 590 6000

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: https://www.facebook.com/cssguncch/
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
