# Site settings
title: contra-bit
subtitle: by Liam Hurwitz
email: liam@contra-bit.com
description: A responsive site template used by contra-bit<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://contra-bit.github.io/forty-jekyll-theme" # the base hostname & protocol for your site
author:Liam Hurwitz
street_address: Vionvillestr. 19
city: Bremen
state: Bremen
zip_code: 28211
country: Deutschland
phone:

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url: https://fb.me/liamhurwitz1
github_url:
gitlab_url:
googleplus_url: https://plus.google.com/u/0/+LiamHurwitz
instagram_url: https://instagram.com/_liam97
linkedin_url: https://www.linkedin.com/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
