# site settings
title: Forty
subtitle: by HTML5 UP
email: samsongoddy@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/samsongoddy
linkedin_url: https://www.linkedin.com/in/samsongoddy
pinterest_url:
slack_url:
twitter_url: https://twitter.com/samson_giddy

# build settings
markdown: kramdown

sass:
  style: compressed
