# site settings
title: Portfolio
subtitle: by Dar√≠o Placencio
email: darioplacenciohidalgo@gmail.com
description: Welcome to my digital portfolio of my work in the fields of Machine Learning and Data Analytics.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: https://placenciohid.github.io # the base hostname & protocol for your site
author:
street_address: 908 Eagle Heights Drive
city: Madison
state: WI
zip_code: 53705
country: United States of America
phone: (608) 800-7317

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/placenciohid/Resume
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/darioplacencio
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
    