# site settings
title: Katelyn Stringer
subtitle: PhD Astronomy Student + Data Analyst
email: youremailaddress@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# contact form settings
form_url: https://formspree.io/youremailaddress@gmail.com # endpoint URL to receive contact form submissions
form_email_name: _replyto # value of the "name" attribute in the "email" field

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
