# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: SHAWN FREY
title-normal: freelance writer
email: shawn.e.frey@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/shawnfrey.github.io" # the subpath of your site, e.g. /blog
url: "www.shawnfrey.press" # the base hostname & protocol for your site
author: 
street_address:
city: Toronto
state: ON
zip_code:
country: Canada
phone: 647.228.3786

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 6

# Social settings
500px_url: 
facebook_url: 
github_url: 
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: andrewbanchich
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 
