# site settings
title: FunPython
subtitle: 
email: admin@ibrain.dev
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: Guayaquil
state: Guayas
zip_code: 
country: Ecuador
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/orgs/FunPythonEC
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/funpython
  LinkedIn: 
  Twitter: https://twitter.com/funpython_ec
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
