# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jason Zutty
subtitle: Research Engineer
email: jasonzutty@gmail.com
personal-email: jasonzutty@gmail.com
work-email: jason.zutty@gtri.gatech.edu
description: >- # this means to ignore newlines until "baseurl:"
  I am a Research Engineer working at Georgia Tech in the field of automated machine learning.
  I spend most of my time developing EMADE, the Evolutionary Multi-objective Algorithm Design Engine.
  This site covers my research work as well as some of my personal hobbies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "jasonzutty.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jasonzutty
github_username:  jasonzutty

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 10

# social settings
500px_url:
facebook_url:
github_url: https://www.github.com/jasonzutty
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://www.instagram.com/jasonzutty
linkedin_url: https://www.linkedin.com/in/jason-zutty-456b6413
#pinterest_url:
#slack_url:
twitter_url: https://www.twitter.com/jasonzutty

# Build settings
markdown: kramdown
#theme: minima

sass:
  style: compressed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
