# site settings
title: Design
subtitle: Thinking
email: sofia@ntoulou.com
description: We are here because we want to learn to COLLABORATE, to do great WORKSHOPS together.<br /> To solve interesting problems with insightful ideas that resonate with PEOPLEâ€™S needs & dreams.<br /> And in doing so, we want to fulfill our CREATIVE potential.<br /> Everything we DESIGN affects people, in one way or another, so we AIM to make a difference.<br /> Now, you may THINK we are dreamers, but we are very practical ones. 
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: AGHIA PARASKEVI
state: ATTICA
zip_code: 15342
country: GREECE
#phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/sofiantoulou
linkedin_url: https://www.linkedin.com/in/sofiantoulou
pinterest_url:
slack_url:
# twitter_url: https://twitter.com/sofiantoulou

# build settings
markdown: kramdown

sass:
  style: compressed
